#ifndef LOOPER_H
#define LOOPER_H

#include <functional>
#include <iostream>
#include <iomanip>
#include <string>
#include <stdlib.h>
#include <getopt.h>

#include "TString.h"
#include "TChain.h"
#include "TFile.h"
#include "TTree.h"
#include "TTreeCache.h"
#include "TTreeCacheUnzip.h"

/**
 * Object for handling HEP CLI input (wraps getopt functionality)
 */
class HEPCLI
{
private:
    /**
     * Display help text
     * @return none
     */
    void printHelp();
    /**
     * Parse command line
     * @param argc argument count
     * @param argv argument vector
     * @return none
     */
    void parse(int argc, char** argv);
public:
    /** Verbosity flag */
    bool verbose;
    /** Name of TTree in input ROOT file(s) */
    std::string input_ttree;
    /** Target directory for output file(s) */
    std::string output_dir;
    /** Short name for output file(s) */
    std::string output_name;
    /** Data (as opposed to Monte Carlo) flag */
    bool is_data;
    /** Signal (as opposed to background) flag */
    bool is_signal;
    /** Debug flag */
    bool debug;
    /** Global event weight */
    float scale_factor;
    /** ROOT TChain with input files */
    TChain* input_tchain;

    /**
     * HEPCLI object constructor
     * @return none
     */
    HEPCLI();

    /**
     * HEPCLI object overload constructor
     * @param argc argument count
     * @param argv argument vector
     * @return none
     */
    HEPCLI(int argc, char** argv);
};

/**
 * Object to handle looping over ROOT files
 */
class Looper
{
protected:
    /** Flag for continuing event loop */
    bool keep_alive;
public:
    /** ROOT TChain of files to loop over */
    TChain* tchain;
    /** ROOT TTree name */
    TString ttree_name;
    /** Current entry in TTree (i.e. current index of event loop) */
    unsigned int current_entry;
    /** Number of events that have been processed */
    unsigned int n_events_processed;
    /** Number of events in the TChain */
    unsigned int n_events_total;
    
    /**
     * Looper object constructor
     * @param new_tchain pointer to ROOT TChain of files to loop over
     * @return none
     */
    Looper(TChain* new_tchain);
    /**
     * Looper object destructor
     * @return none
     */
    virtual ~Looper();
    /**
     * Run looper with file- and event-processing logic captured in void lambda functions.
     *
     * The following example uses a class named "Selector" generated by ROOT::MakeSelector;
     * this class requires certain file- and event-processing initialization steps:
     * @code{.cpp}
     * int main()
     * {
     *     TChain* tchain = new TChain("Events");
     *     tchain->Add("/path/to/file.root");
     *     selector = Selector(); // generated by ROOT::MakeSelector
     *     looper = Looper(tchain, "Events");
     *     looper.run(
     *         [&](TTree* ttree) { selector.Init(ttree); },
     *         [&](int entry) 
     *         {
     *             selector.GetEntry(entry);
     *             selector.Process(entry);
     *             // -> insert your favorite cutflow here <--
     *         }
     *     );
     * }
     * @endcode
     * @param init file-level initialization steps captured in a void lambda function
     * @param eval event-level logic captured in a void lambda function
     * @return none
     */
    void run(std::function<void(TTree* ttree)> init, std::function<void(int entry)> eval);

    /**
     * Stop event loop
     * @return none
     */
    void stop();
};

#include "looper.icc"

#endif
