name: Build and push RAPIDO docs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone RAPIDO
        run: git clone https://github.com/jkguiang/rapido.git
      - name: Clone RAPIDO docs
        uses: actions/checkout@v3
        with:
          ref: "docs"
          path: "./rapido-docs"
          submodules: true
      - name: Build docs
        uses: mattnotmitt/doxygen-action@v1.9.3
        with:
          working-directory: "./rapido-docs"
          doxyfile-path: "doxyfile"
      - name: Commit docs
        uses: EndBug/add-and-commit@v8
        with:
          add: "['html', 'latex']"
          cwd: "./rapido-docs"
          message: "automated docs update"
          push: "origin docs"
